---
- name: Configure DevOps Server
  hosts: all
  become: yes  # Run as root

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      
    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes