name: Deploy Flask App

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - uses: actions/checkout@v3
    
    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    # Build and push Docker image
    - name: Build and push
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/flask-devops-app:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-devops-app:${{ github.sha }}
    
    # Deploy to Kubernetes (using existing k8s configs)
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/