name: Deploy Flask App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # Set up Minikube
    - name: Set up Minikube
      run: |
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        sudo install minikube-linux-amd64 /usr/local/bin/minikube
        minikube start --driver=docker
        
    # Build and push Docker image (existing step)
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/flask-devops-app:${{ github.sha }} .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/flask-devops-app:${{ github.sha }}
    
    # Deploy to Minikube
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/
        minikube service flask-service --url